package com.fam.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Component;

/**
 * Paramast generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Component
@Table(name = "paramast", schema = "public")
public class Paramast implements java.io.Serializable {

 @Id
@SequenceGenerator(name = "paramast_sequence_generator", sequenceName = "paramast_recordid_seq",allocationSize = 1)
 @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "paramast_sequence_generator")
	private long recordid;
	private String paratype;
	private String paraname;
	private String code;
	private String sdesc;
	private String ldesc;
	private String allowuser;
	private String remarks;
	private String extras1;
	private String extras2;
	private String recstatus;
	private String makerid;
	private Date makerdate;
	private String makertime;
	private String makerip;
	private String checkerid;
	private Date checkerdate;
	private String checkertime;
	private String checkerip;
	private String approverid;
	private Date approverdate;
	private String approvertime;
	private String approverip;

	public Paramast() {
	}

	public Paramast(long recordid) {
		this.recordid = recordid;
	}

	public Paramast(long recordid, String paratype, String paraname, String code, String sdesc, String ldesc,
			String allowuser, String remarks, String extras1, String extras2, String recstatus, String makerid,
			Date makerdate, String makertime, String makerip, String checkerid, Date checkerdate, String checkertime,
			String checkerip, String approverid, Date approverdate, String approvertime, String approverip) {
		this.recordid = recordid;
		this.paratype = paratype;
		this.paraname = paraname;
		this.code = code;
		this.sdesc = sdesc;
		this.ldesc = ldesc;
		this.allowuser = allowuser;
		this.remarks = remarks;
		this.extras1 = extras1;
		this.extras2 = extras2;
		this.recstatus = recstatus;
		this.makerid = makerid;
		this.makerdate = makerdate;
		this.makertime = makertime;
		this.makerip = makerip;
		this.checkerid = checkerid;
		this.checkerdate = checkerdate;
		this.checkertime = checkertime;
		this.checkerip = checkerip;
		this.approverid = approverid;
		this.approverdate = approverdate;
		this.approvertime = approvertime;
		this.approverip = approverip;
	}

	@Id

	@Column(name = "recordid", unique = true, nullable = false)
	public long getRecordid() {
		return this.recordid;
	}

	public void setRecordid(long recordid) {
		this.recordid = recordid;
	}

	@Column(name = "paratype", length = 10)
	public String getParatype() {
		return this.paratype;
	}

	public void setParatype(String paratype) {
		this.paratype = paratype;
	}

	@Column(name = "paraname", length = 50)
	public String getParaname() {
		return this.paraname;
	}

	public void setParaname(String paraname) {
		this.paraname = paraname;
	}

	@Column(name = "code", length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "sdesc", length = 20)
	public String getSdesc() {
		return this.sdesc;
	}

	public void setSdesc(String sdesc) {
		this.sdesc = sdesc;
	}

	@Column(name = "ldesc")
	public String getLdesc() {
		return this.ldesc;
	}

	public void setLdesc(String ldesc) {
		this.ldesc = ldesc;
	}

	@Column(name = "allowuser", length = 1)
	public String getAllowuser() {
		return this.allowuser;
	}

	public void setAllowuser(String allowuser) {
		this.allowuser = allowuser;
	}

	@Column(name = "remarks", length = 200)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "extras1", length = 200)
	public String getExtras1() {
		return this.extras1;
	}

	public void setExtras1(String extras1) {
		this.extras1 = extras1;
	}

	@Column(name = "extras2", length = 200)
	public String getExtras2() {
		return this.extras2;
	}

	public void setExtras2(String extras2) {
		this.extras2 = extras2;
	}

	@Column(name = "recstatus", length = 1)
	public String getRecstatus() {
		return this.recstatus;
	}

	public void setRecstatus(String recstatus) {
		this.recstatus = recstatus;
	}

	@Column(name = "makerid", length = 10)
	public String getMakerid() {
		return this.makerid;
	}

	public void setMakerid(String makerid) {
		this.makerid = makerid;
	}

		@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Column(name = "makerdate", length = 13)
	public Date getMakerdate() {
		return this.makerdate;
	}

	public void setMakerdate(Date makerdate) {
		this.makerdate = makerdate;
	}

	@Column(name = "makertime", length = 8)
	public String getMakertime() {
		return this.makertime;
	}

	public void setMakertime(String makertime) {
		this.makertime = makertime;
	}

	@Column(name = "makerip", length = 15)
	public String getMakerip() {
		return this.makerip;
	}

	public void setMakerip(String makerip) {
		this.makerip = makerip;
	}

	@Column(name = "checkerid", length = 10)
	public String getCheckerid() {
		return this.checkerid;
	}

	public void setCheckerid(String checkerid) {
		this.checkerid = checkerid;
	}

		@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Column(name = "checkerdate", length = 13)
	public Date getCheckerdate() {
		return this.checkerdate;
	}

	public void setCheckerdate(Date checkerdate) {
		this.checkerdate = checkerdate;
	}

	@Column(name = "checkertime", length = 8)
	public String getCheckertime() {
		return this.checkertime;
	}

	public void setCheckertime(String checkertime) {
		this.checkertime = checkertime;
	}

	@Column(name = "checkerip", length = 15)
	public String getCheckerip() {
		return this.checkerip;
	}

	public void setCheckerip(String checkerip) {
		this.checkerip = checkerip;
	}

	@Column(name = "approverid", length = 10)
	public String getApproverid() {
		return this.approverid;
	}

	public void setApproverid(String approverid) {
		this.approverid = approverid;
	}

		@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Column(name = "approverdate", length = 13)
	public Date getApproverdate() {
		return this.approverdate;
	}

	public void setApproverdate(Date approverdate) {
		this.approverdate = approverdate;
	}

	@Column(name = "approvertime", length = 8)
	public String getApprovertime() {
		return this.approvertime;
	}

	public void setApprovertime(String approvertime) {
		this.approvertime = approvertime;
	}

	@Column(name = "approverip", length = 15)
	public String getApproverip() {
		return this.approverip;
	}

	public void setApproverip(String approverip) {
		this.approverip = approverip;
	}

}
